config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'precipes#index'

  resources :foods
  resources :recipes do
    resources :recipe_foods
  end

  get '/general_shopping_list', to: 'foods#general', as: 'general'


  # Defines the root path route ("/")

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, :all, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :measurement_unit, presence: true, length: { maximum: 20 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :cooking_time, presence: true, length: { maximum: 20 }
  validates :preparation_time, presence: true, length: { maximum: 20 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates_associated :foods
  validates_associated :recipes
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :name, length: { minimum: 2 }
  validates :password, length: { minimum: 6 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_user

  def index
    @foods = @user.foods
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = @user.foods.new(food_params)

    if @food.save
      redirect_to foods_path, notice: 'New Food successfully added.'
    else
      flash[:alert] = 'Food adding Failed. Please try again.'
    end
  end

  def edit
    @food = @user.foods.find(params[:id])
  end

  def update
    @food = @user.foods.find(params[:id])
    if @food.update(food_params)
      redirect_to foods_path, notice: 'Food was successfully updated.'
    else
      flash[:alert] = 'Food updating Failed. Please try again.'
    end
  end

  def destroy
    food = Food.find(params[:id])

    return flash[:alert] = 'You do not have permission to delete this food as it belongs to another user' unless (food.user = @user)

    if food.destroy
      flash[:notice] = 'Food deleted successfully.'
    else
      flash[:alert] = 'Food deleting Failed. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def general
    @foods = @user.foods
    @user.recipes.map do |recipe|
      recipe.recipe_foods.map do |recipe_food|
        food = recipe_food.food
        test = @foods.select { |f| f.name == food.name }[0]
        test.quantity = test.quantity - recipe_food.quantity
      end
    end
    @foods = @foods.select { |f| f.quantity.negative? }
    @foods.each { |f| f.quantity *= -1 }
    @total = 0
    @foods.each do |food|
      @total += (food.price * food.quantity)
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :quantity, :measurement_unit, :price)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/precipes_controller.rb
class PrecipesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_user
  def index
    @recipes = Recipe.where(public: true)
  end

  def show; end

  private

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_user

  def new
    recipe = Recipe.find(params[:recipe_id])
    unless recipe.user == current_user
      flash[:alert] =
        'You do not have access to add an ingredient on a recipe that does not belong to you.'
      return redirect_to recipes_path
    end

    @recipe_food = RecipeFood.new
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.recipe = @recipe

    if recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'New ingredient added successfully.'
    else
      flash[:alert] = 'New Ingredient adding Failed. Please try again.'
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])

    unless recipe_food.recipe.user == current_user
      flash[:alert] =
        'You can not delete the ingredient that you did not add'
      return redirect_to recipes_path
    end

    if recipe_food.destroy
      flash[:notice] = 'Ingredient was successfully deleted.'
    else
      flash[:alert] = 'Ingredient deleting failed. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user
  before_action :set_recipe, only: %i[show destroy]

  def index
    @recipes = @user.recipes
  end

  def show; end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @user
    @recipe.public = true
    if @recipe.save
      redirect_to recipes_path, notice: 'recipe created successfully'
    else
      render :new, notice: 'notsaved'
    end
  end

  def update
    @recipe.update(public: params[:checkbox_input])
    respond_to do |format|
      format.html { redirect_to @recipe }
      format.js
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end

  def create; end

  def destroy; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <br/>

  <div class="field form-group">
    
    <%= form.text_field :measurement_unit, class:"form-control", placeholder:"Measurement Unit" %>
  </div>

  <br/>

  <div class="field form-group">
    
    <%= form.text_field :price, class:"form-control", placeholder:"Price" %>
  </div>

  <br/>

  <div class="field form-group">
    
    <%= form.text_field :quantity, class:"form-control", placeholder:"Quantity" %>
  </div>

  <br/>
  
  <div class="field form-group">
    
    <%= form.number_field :user_id, id: :food_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  
<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<!-- component -->
<div>
	<div>
		<div>
			<div>
				<div>
					<h1>Edit Your Food</h1>
                     <% if @food.errors.any? %>
                            <ul>
                            <% @food.errors.full_messages.each do |msg|%>
                            <li><%= msg %></li>
                            <% end %>
                            </ul>
                    <% end %>
   
				</div>
				<%= render 'form', food: @food %>
            </div>
        </div>
    </div>
</div>

app/views/foods/general.html.erb
<div class="nice">
<h3 class="heading">Shopping List</h3>
<div class="awesome">
  <div class='rest'>
  <span>Amount of food items to buy: </span>
  <span>&nbsp;<%= @foods.length %></span>
  </div>

  <div class='rest'>
  <span>Total value of food needed:</span>
  <span>&nbsp;<%= @total %>$</span>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Value</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
         <td><%= food.quantity %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %>$</td>
        <td><%= button_to "Delete", food_path(food.id), data: {turbo_method: :delete, turbo_confirm: 'are you sure'}, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/foods/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit price($)</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <% if food.user == current_user %>
        <tr>
          <td>
<%= food.name %>


          </td>
          
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td><%= food.quantity %></td>
          <td>
							<span class="col-xs-6 text-left">
								<i><%= link_to "edit", edit_food_path(food) %></i>
						    </span>

							<span class="col-xs-6 text-right">
								<i><%= button_to "Delete", food_path(food.id), method: :delete, data: { confirm: "Are you sure?" }, id: "delete_button" %></i>
						    </span>
						</td>

          <%
=begin%>
 <td><%= link_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td> 
<%
=end%>
          
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add Food', new_food_path, class:"btn btn-secondary" %>
<% else %>

<h1>Hello World!</h1>

<% end %>

app/views/foods/new.html.erb
<h1>Add New Food</h1>
<br/>
<%= render 'form', food: @food %>

<br/>
<%= link_to 'Back', foods_path, class:"btn btn-dark" %>

app/views/foods/show.html.erb
<h1>Food Show Page is here</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LushRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container p-5">
    <%= yield %>
    </div>
  </body>
</html>

app/views/precipes/index.html.erb
<%if @recipes.empty?%>
      <div class="card mb-3 border-danger" style="width: 540px;">
        <div class="card-header bg-danger text-white">Empty</div>
        <div class="card-body">
          <h5 class="card-title text-danger">there is no public recipes yet</h5>
      </div>
      </div>
  <%else%>
  <%= render partial: "recipes/recipe",  collection: @recipes %>
  <%end%>

app/views/precipes/show.html.erb
<h1>PublicRecipes#show</h1>
<p>Find me in app/views/public_recipes/show.html.erb</p>

app/views/recipe_foods/new.html.erb
<div>
  <%= form_with url: recipe_recipe_foods_path, scope: :recipe_food do |form| %>
    <p>Add Ingredient</p>
    <div>
      <%= form.label :quantity, "Quantity", placeholder: 0 %>
      <%= form.number_field :quantity %>
    </div>
    <div>
      <%= form.label :food_id, "Food" %>
      <div>
        <%= form.collection_select :food_id, @foods, :id, :name %>
      </div>
    </div>
    <div>
      <%= form.submit "Add Ingredient", id: "add_ingredient" %>
    </div>
  <% end %>
</div>

app/views/recipes/_recipe.html.erb
<div class="card mb-3" style="width: 28rem;">
  <div class="card-body">
    <h5 class="card-title"><%=recipe.name%></h5>
    <h6 class="card-subtitle mb-2 text-muted">By.<%=recipe.user.name%></h6>
    <p class="card-text"><%=recipe.description%></p>
    <%= link_to"See Details", recipe_path(recipe),calss: "mb-3"%>
    <%if can? :delete, recipe%>
    <%= button_to 'delete', recipe_path(recipe), method: :delete,class:"btn btn-secondary" %>
    <%end%>
  </div>
</div>

app/views/recipes/index.html.erb
<%if @recipes.empty?%>
      <div class="card mb-3 border-danger" style="width: 540px;">
        <div class="card-header bg-danger text-white">Empty</div>
        <div class="card-body">
          <h5 class="card-title text-danger">You have no recipe yet, Please create one</h5>
      </div>
      </div>
  <%else%>
  <%= render @recipes %>
  <%end%>

  <%= link_to "Create a new Recipe", new_recipe_path, class:"mt-5" %>

app/views/recipes/new.html.erb
<h2>Create a new Recipe </h2>

<%= form_with model: @recipe do |f| %>
  <div class="mb-3">
    <%= f.label :name, class:"label-control" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :preparation_time, class:"label-control" %>
    <%= f.text_field  :preparation_time, class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :cooking_time, class:"label-control" %>
    <%= f.text_field :cooking_time, class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :description, class:"label-control" %>
    <%= f.text_field :description, class:"form-control" %>
  </div>
  <%=f.submit "create", class:"btn btn-light"%>
<% end %> 
<%= link_to "back", recipes_path %>

app/views/recipes/show.html.erb
<div class="card" style="width: 25rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @recipe.name%></h5>
    <h6 class="card-subtitle mb-2 text-muted">By time: <%=@recipe.user.name%></h6>
    <p class="card-text">Preparation time: <%=@recipe.preparation_time%>.</p>
    <p class="card-text">Cooking time: <%= @recipe.cooking_time%>.</p>
    <%= link_to 'Generate Shopping List', general_path, data: {turbo_method: :post}, class:"card-link" %>
    <%if can? :manag, @recipe%>
       <%= link_to "Add ingredients",new_recipe_recipe_food_path(@recipe), class:"card-link"%> 
    <%end%>
    <div class="col-md-4">
    <% if can? :update, @recipe %>
      <%= form_with model:@recipe, url:recipe_path(@recipe), html:{method: :put} do |f| %>
        <button type="submit" class="btn" id="recipe_public">
          <div class="form-check form-switch">
            <%= f.label :public, class:"form-check-label" %>
            <%= f.check_box :public, class:"form-check-input" %>
          </div>
        </button>
      <% end %>
    <% end %>
  </div>
  <table class='table'>
  <% if @recipe.recipe_foods.any? %>
     <thead>
         <tr>
         <th>Food</th>
         <th>Quantity</th>
         <th>Value</th>
         <th>Action</th>
         </tr>
     </thead>
     <tbody>
     <% @recipe.recipe_foods.each do |food|%>
     <tr>
       <td><%= food.food.name%></th>
       <td><%= food.quantity%></td>
       <td><%= food.quantity * food.food.price %></td>
       <td>
         <%=button_to "Delete", recipe_recipe_food_path(@recipe, food), data: {turbo_method: :delete, turbo_confirm: 'are you sure'}, method: :delete%>
       </td>
     </tr>
     <%end%>
     </tbody>
   <%end%>
 </table>
 <%=link_to "Back", recipes_path %>
 </div>
  

app/views/shared/_details.html.erb
<div>
<h2><%= recipe.name%> </h2>
<span>by recipe.user.name </span>

<div>Preparation time: <%=@recipe.preparation_time%></div>
<div>Cooking time:<%= recipe.cooking_time%></div>
<%= link_to "Steps Goes here",recipe_path(recipe)  %>
<div class="form-check form-switch">
  <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
  <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
  # <link_to "Generate shopping list", %>

  <% if can? :manag ,recipe %>
  <div> add ingredients<div>

  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light ps-5 pe-5">
<div class="container-fluid">
  <%= link_to "Lush Recipies", root_path,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav w-100">
    <div class="d-flex justify-content-between w-100">
      <div class="d-flex">
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Foods", foods_path, class:"nav-link"%>
        </li>
      </div>
        <% if !user_signed_in? %>
      <div class="d-flex">
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class:"nav-link"%>
        </li>
        <%else %>
        <div class="d-flex">
        <li class="nav-item"> <li class="nav-link">Logged in as  <%=@user.name%> </li></li>
        <li class="nav-item">
            <%= button_to 'Log out', destroy_user_session_path, method: :delete , data: { turbo: false }, class:"nav-link btn btn-light" %>
        </li>
        </div>
      </div>
      <%end %>
    </div>


    </ul>
  </div>
</div>
</nav>

app/views/shared/_recipe.html.erb
<div class="card mb-3 border-success" style="width: 540px;">
  <%= link_to recipe_path(recipe) do%>
      <div class="card-header bg-success text-white"><%=recipe.name%></div>
      <div class="card-body">
          <p class="card-text"><%=recipe.description%> </p>
      </div>
  <% end %>
  <% if can? :manag, recipe %>
  <div class='card-footer d-flex gap-2 justify-content-end'>
  <%= button_to 'delete', recipe_path(recipe), method: :delete,class:"btn btn-secondary" %>
  </div>
  <%end%>
</div>

app/views/users/index.html.erb
<h1>Hi there!</h1>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>